-- The grain table
CREATE TABLE grains (
    id INTEGER PRIMARY KEY,
    file TEXT NOT NULL,
    start_frame INTEGER NOT NULL,
    end_frame INTEGER NOT NULL,
    sample_rate INTEGER NOT NULL,
    grain_duration REAL NOT NULL,
    frequency REAL,
    midi REAL,
    spectral_centroid REAL NULL,
    spectral_entropy REAL NOT NULL,
    spectral_flatness REAL NOT NULL,
    spectral_kurtosis REAL NOT NULL,
    spectral_roll_off_50 REAL NOT NULL,
    spectral_roll_off_75 REAL NOT NULL,
    spectral_roll_off_90 REAL NOT NULL,
    spectral_roll_off_95 REAL NOT NULL,
    spectral_skewness REAL NOT NULL,
    spectral_slope REAL NOT NULL,
    spectral_slope_0_1_khz REAL NOT NULL,
    spectral_slope_1_5_khz REAL NOT NULL,
    spectral_slope_0_5_khz REAL NOT NULL,
    spectral_variance REAL NOT NULL
);
