wireplumber.settings = {
  node.rules = [
    {
      matches = [
        {
          node.name = "SuperCollider"
        }
      ]
      actions = {
        merge = {
          node.autoconnect = false
        }
      }
    }
  ]
}
