wireplumber.components = [
  {
    name = "/home/jeff/.config/wireplumber/scripts/focusrite-sc.lua",
    type = script/lua
    provides = focusrite-supercollider
  },
  {
    name = "/home/jeff/.config/wireplumber/scripts/focusrite-reaper.lua",
    type = script/lua,
    provides = focusrite-reaper
  }
]

wireplumber.profiles = {
  main = {
    focusrite-supercollider = required
    focusrite-reaper = required
  }
}
