wireplumber.components = [
  {
    name = "/home/jeff/.config/wireplumber/scripts/focusrite-sc.lua",
    type = script/lua
    provides = studio-x
  }
]

wireplumber.profiles = {
  main = {
    studio-x = required
  }
}
