wireplumber.components = [
  {
    name = "/home/jeff/.config/wireplumber/scripts/focusrite-sc.lua",
    type = script/lua
    provides = studio-x-supercollider
  },
  {
    name = "/home/jeff/.config/wireplumber/scripts/focusrite-reaper.lua",
    type = script/lua
    provides = studio-x-reaper
  }
]

wireplumber.profiles = {
  main = {
    studio-x-supercollider = required,
    studio-x-reaper = required
  }
}
